name: Extract RootFS from Docker Image

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-latest-arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile . -t fedora

      - name: Extract RootFS
        run: |
          docker create --name fedora fedora echo "Fedora Linux"
          docker export -o rootfs.$(dpkg --print-architecture).tar fedora
          gzip rootfs.$(dpkg --print-architecture).tar
          docker rm fedora

      - name: Upload RootFS
        uses: actions/upload-artifact@v4
        with:
          name: rootfs-${{ matrix.os }}
          path: rootfs.*.tar.gz

  release:
    name: Release
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download RootFS
        id: download-rootfs
        uses: actions/download-artifact@v3
        with:
          name: rootfs-ubuntu-latest, rootfs-ubuntu-latest-arm64
          path: rootfs

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          prerelease: false
          files: |
            ${{ steps.download-rootfs.outputs.download-path }}/*.tar.gz
